version: "3.8"
services:
  frontend:
    build:
      context: ./frontend # Path to your frontend directory
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend # Path to your backend directory
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
